/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.views.modals;

import com.mycompany.models.Cliente;
import com.mycompany.models.ConsultaActionModes;
import com.mycompany.models.ConsultaDialogModes;
import com.mycompany.models.Producto;
import com.mycompany.models.Venta;
import com.mycompany.models.Compra;
import com.mycompany.models.Proveedor;
import com.mycompany.services.ClientesService;
import com.mycompany.services.CompraService;
import com.mycompany.services.ProductosService;
import com.mycompany.services.ProveedorService;
import com.mycompany.services.VentaService;
import com.mycompany.views.modals.ClienteDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author PC
 */
public class ConsultarDialog extends javax.swing.JDialog {

    /**
     * Creates new form consultarDialog
     */
    ClientesService _clientesService;
    ConsultaActionModes action_mode;
    ConsultaDialogModes mode;
    int mPosX, mPosY;
    String placeH;

    public ConsultarDialog(java.awt.Frame parent, boolean modal, ClientesService service, ConsultaDialogModes _mode, ConsultaActionModes action_mode) {
        super(parent, modal);
        initComponents();
        this._clientesService = service;
        this.action_mode = action_mode;
        this.mode = _mode;

        if (this.action_mode == ConsultaActionModes.ELIMINAR) {

            this.btnAceptar.setText("Eliminar");
        }
        switch (mode) {
            case ConsultaDialogModes.Producto:
                lblNIT.setText("Código");
                lblTitle.setText("Gestionar producto");
                txtNIT.setText("Ingresa el código de producto");
                break;
            case ConsultaDialogModes.Compra:
                lblNIT.setText("ID Compra");
                lblTitle.setText("Consultar Compra");
                txtNIT.setText("Ingresa el id de compra");
                break;
            case ConsultaDialogModes.Venta:
                lblNIT.setText("ID Venta");
                lblTitle.setText("Consultar Venta");
                txtNIT.setText("Ingresa el id de la venta");
                break;
            case ConsultaDialogModes.Proveedor:
                lblNIT.setText("ID");
                lblTitle.setText("Consultar proveedor");
                txtNIT.setText("Ingresa el id de proveedor");
                break;

        }
        this.placeH = this.txtNIT.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblNIT = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        btnCerrarWindow = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 256));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(450, 256));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNIT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNIT.setForeground(new java.awt.Color(33, 33, 33));
        lblNIT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNIT.setText("NIT");
        lblNIT.setFocusCycleRoot(true);
        background.add(lblNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 60, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(33, 33, 33));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Consultar");
        background.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 430, -1));

        txtNIT.setForeground(new java.awt.Color(204, 204, 204));
        txtNIT.setText("Ingrese el NIT");
        txtNIT.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtNIT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNITnone(evt);
            }
        });
        txtNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNITKeyTyped(evt);
            }
        });
        background.add(txtNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, -1));

        btnAceptar.setBackground(new java.awt.Color(13, 110, 253));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setLabel("Aceptar");
        btnAceptar.setPreferredSize(new java.awt.Dimension(30, 45));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        background.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, 30));

        btnCancelar.setBackground(new java.awt.Color(220, 53, 69));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        background.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 100, 30));

        header.setBackground(new java.awt.Color(33, 33, 33));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/src/test.png"))); // NOI18N
        btnCerrarWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarWindowMouseClicked(evt);
            }
        });
        header.add(btnCerrarWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 30));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        jSeparator3.setBackground(new java.awt.Color(30, 30, 30));
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNITnone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNITnone
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNITnone

    private void txtNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNITKeyTyped
        // TODO add your handling code here:
        //Limpiar el placeholder al escribir dentro del field
        if (txtNIT.getText().equals(this.placeH)) {
            txtNIT.setText("");
        }
    }//GEN-LAST:event_txtNITKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        System.out.println("Dialog: " + this.mode);
        String nit = txtNIT.getText();
        if (this.mode == ConsultaDialogModes.Cliente) {
            ClienteDialog _dialog;
            Cliente _cliente = null;
            if (this.action_mode == ConsultaActionModes.ACTUALIZAR || this.action_mode == ConsultaActionModes.CONSULTAR) {
                String data[] = _clientesService.consultarCliente(nit);
                _cliente = new Cliente(data[0], data[1], data[2], data[3], data[4]);
                _dialog = new ClienteDialog(null, true, _cliente, this.action_mode);
                _dialog.setAlwaysOnTop(true);
                _dialog.setLocationRelativeTo(null);
                this.dispose();
                _dialog.setVisible(true);
            } else if (this.action_mode == ConsultaActionModes.ELIMINAR) {
                this.setAlwaysOnTop(false);
                if (this._clientesService.eliminarCliente(nit)) {
                    JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha podido eliminar el cliente");
                }
                this.dispose();

            }
        } else if (this.mode == ConsultaDialogModes.Producto) {

            ProductoDialog _dialog;
            if (this.action_mode == ConsultaActionModes.ACTUALIZAR || this.action_mode == ConsultaActionModes.CONSULTAR) {
                Producto producto = ProductosService.Get(nit);
                _dialog = new ProductoDialog(null, true, producto, this.action_mode);
                _dialog.setAlwaysOnTop(true);
                _dialog.setLocationRelativeTo(null);
                this.dispose();
                _dialog.setVisible(true);
            } else if (this.action_mode == ConsultaActionModes.ELIMINAR) {
                this.setAlwaysOnTop(false);
                if (ProductosService.Delete(nit)) {
                    JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha podido eliminar el cliente");
                }
                this.dispose();

            }
        } else if (this.mode == ConsultaDialogModes.Venta) {

            Venta v = VentaService.getVenta(Integer.parseInt(nit));
            System.out.println("Venta en Client: "); 
            v.getDetalles().forEach(p-> System.out.println(p.getCodigoProducto()));
            VentaDialog _dialog = new VentaDialog(null, true, v, this.action_mode);
            _dialog.setAlwaysOnTop(true);
            _dialog.setLocationRelativeTo(null);
            this.dispose();
            _dialog.setVisible(true);
        }
        else if (this.mode == ConsultaDialogModes.Proveedor){
                Proveedor proveedor = ProveedorService.get(Integer.parseInt(nit));
                ProveedorDialog _dialog;
                _dialog = new ProveedorDialog(null, true, proveedor, this.action_mode);
                _dialog.setAlwaysOnTop(true);
                _dialog.setLocationRelativeTo(null);
                this.dispose();
                _dialog.setVisible(true);
        }
        else if (this.mode == ConsultaDialogModes.Compra){
            Compra compra = CompraService.getCompra(Integer.parseInt(nit));
            compra.getDetalles().forEach(p-> System.out.println(p.getCodigo_producto()));
            CompraDialog _dialog = new CompraDialog(null, true, compra, this.action_mode);
            _dialog.setAlwaysOnTop(true);
            _dialog.setLocationRelativeTo(null);
            this.dispose();
            _dialog.setVisible(true);
        }


    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarWindowMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarWindowMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        this.mPosX = evt.getX();
        this.mPosY = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int newPos[] = {mPosX, mPosY};
        this.setLocation(evt.getXOnScreen() - mPosX, evt.getYOnScreen() - mPosY);
    }//GEN-LAST:event_headerMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarDialog dialog = new ConsultarDialog(new javax.swing.JFrame(), true, new ClientesService(), ConsultaDialogModes.Cliente, ConsultaActionModes.CONSULTAR);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnCerrarWindow;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblNIT;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtNIT;
    // End of variables declaration//GEN-END:variables
}
