/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.views.modals;

import com.mycompany.models.Producto;
import com.mycompany.models.ConsultaActionModes;
import com.mycompany.models.Proveedor;
import com.mycompany.services.ClientesService;
import com.mycompany.services.ProductosService;
import com.mycompany.services.ProveedorService;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class ProductoDialog extends javax.swing.JDialog {

    /**
     * Creates new form ClienteDialog
     */
    String codigoPH = "";
    String nombrePH = "";
    Producto _producto = null;
    ConsultaActionModes modo = ConsultaActionModes.CREAR;
    int mPosX;
    int mPosY;

    public ProductoDialog(java.awt.Frame parent, boolean modal, Producto producto, ConsultaActionModes modo) {
        super(parent, modal);
        initComponents();
        this.modo = (modo != null) ? modo : null;
        codigoPH = this.txtCodigo.getText();
        nombrePH = this.txtNombre.getText();
        cargarProveedores();
        if (modo == ConsultaActionModes.CONSULTAR) {
            _producto = producto;
            lblTitle.setText("Producto Consultado");
            btnCrear.setText("Aceptar");
            jPanel1.remove(btnCancelar);
            jPanel1.revalidate();
            jPanel1.repaint();
            establecerNoEditableTodo();
            rellenarDatos();
        } else if (modo == ConsultaActionModes.ACTUALIZAR) {
            _producto = producto;
            this.txtCodigo.setEditable(false);
            lblTitle.setText("Actualizar");
            this.btnCrear.setText("Actualizar");

            rellenarDatos();
        }

    }
    
    private void cargarProveedores(){
        ArrayList<Proveedor> listProveedores = ProveedorService.getAll();
        listProveedores.forEach((p)->cboxProveedor.addItem(p.getNombre()));
    }
    private void establecerNoEditableTodo() {
        txtCodigo.setEditable(false);
        txtNombre.setEditable(false);
        spnPrecioCompra.setEnabled(false);
        spnPrecioVenta.setEnabled(false);
        cboxProveedor.setEnabled(false);
        spnDisponible.setEnabled(false);
    }

    private void rellenarDatos() {
        txtCodigo.setText(_producto.getCodigo());
        txtNombre.setText(_producto.getNombre());
        spnPrecioCompra.setValue(_producto.getPrecio_Compra());
        spnPrecioVenta.setValue(_producto.getPrecio_Venta());
        cboxProveedor.setSelectedItem(_producto.getProveedor());
        spnDisponible.setValue(_producto.getDisponible());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblNIT = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDirección = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnCerrarWindow = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(100, 32767));
        cboxProveedor = new javax.swing.JComboBox<>();
        spnPrecioCompra = new javax.swing.JSpinner();
        spnPrecioVenta = new javax.swing.JSpinner();
        lblDisponible = new javax.swing.JLabel();
        spnDisponible = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(246, 246, 246));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNIT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNIT.setForeground(new java.awt.Color(33, 33, 33));
        lblNIT.setText("Código");
        lblNIT.setFocusCycleRoot(true);
        background.add(lblNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Crear Producto");
        background.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 40, 570, -1));

        txtCodigo.setForeground(new java.awt.Color(204, 204, 204));
        txtCodigo.setText("Ingrese el código de producto");
        txtCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtCodigo.setCaretColor(new java.awt.Color(51, 51, 51));
        txtCodigo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigonone(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        background.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 170, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(33, 33, 33));
        lblNombre.setText("Nombre");
        lblNombre.setFocusCycleRoot(true);
        background.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Ingrese el nombre del producto");
        txtNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombrenone(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        background.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        lblDirección.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDirección.setForeground(new java.awt.Color(33, 33, 33));
        lblDirección.setText("Proveedor");
        lblDirección.setFocusCycleRoot(true);
        background.add(lblDirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(33, 33, 33));
        lblCorreo.setText("Precio de venta");
        lblCorreo.setFocusCycleRoot(true);
        background.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(33, 33, 33));
        lblTelefono.setText("Precio de compra");
        lblTelefono.setFocusCycleRoot(true);
        background.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        header.setBackground(new java.awt.Color(33, 33, 33));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/src/test.png"))); // NOI18N
        btnCerrarWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarWindowMouseClicked(evt);
            }
        });
        header.add(btnCerrarWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 30));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 30));

        jSeparator3.setBackground(new java.awt.Color(30, 30, 30));
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, 10));

        jSeparator4.setBackground(new java.awt.Color(30, 30, 30));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 170, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 50, 0));
        jPanel1.add(filler2);

        btnCrear.setBackground(new java.awt.Color(13, 110, 253));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.setPreferredSize(new java.awt.Dimension(30, 45));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear);

        btnCancelar.setBackground(new java.awt.Color(220, 53, 69));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        jPanel1.add(filler1);

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 580, 30));

        cboxProveedor.setBackground(new java.awt.Color(255, 255, 255));
        cboxProveedor.setForeground(new java.awt.Color(117, 117, 117));
        background.add(cboxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 190, -1));

        spnPrecioCompra.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        background.add(spnPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 60, 20));

        spnPrecioVenta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        background.add(spnPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, 20));

        lblDisponible.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDisponible.setForeground(new java.awt.Color(33, 33, 33));
        lblDisponible.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDisponible.setText("Disponible");
        lblDisponible.setFocusCycleRoot(true);
        background.add(lblDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, -1));

        spnDisponible.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        background.add(spnDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigonone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigonone
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigonone

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        //Limpiar el placeholder al escribir dentro del field
        if (txtCodigo.getText().equals(codigoPH)) {
            txtCodigo.setText("");
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtNombrenone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombrenone
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrenone

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        if (txtNombre.getText().equals(nombrePH)) {
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Producto p = new Producto();
        String nombre = txtNombre.getText();
        String codigo = txtCodigo.getText();
        int precio_venta = (int) spnPrecioVenta.getValue();
        int precio_compra = (int) spnPrecioCompra.getValue();
        int proveedor_id = cboxProveedor.getSelectedIndex() + 1;
        int disponible = (int) spnDisponible.getValue();
        p.setCodigo(codigo);
        p.setNombre(nombre);
        p.setPrecio_Compra(precio_compra);
        p.setPrecio_Venta(precio_venta);
        p.setDisponible(disponible);
        p.setProveedor_id(proveedor_id);
        switch (this.modo) {
            case CREAR:
                if(nombre.isEmpty() || codigo.isEmpty() || precio_venta == 0 || precio_compra == 0) {
                    JOptionPane.showMessageDialog(null, "No puede dejar los campos en blanco");
                    this.dispose();
                    return;

                } else {
                    this.setModal(false);
                    this.setAlwaysOnTop(false);
                    ProductosService.Post(codigo, nombre, disponible,precio_compra, precio_venta, proveedor_id);
                    JOptionPane.showMessageDialog(null, "Se ha creado correctamente");
                    this.dispose();
                }
                break;
            case CONSULTAR:
                this.dispose();
                break;
            case ACTUALIZAR:
                if (nombre.isEmpty()  || precio_venta == 0 || precio_compra == 0) {
                    JOptionPane.showMessageDialog(null, "No puede dejar los campos en blanco");
                    this.dispose();
                    return;

                } else {
                    this.setModal(false);
                    this.setAlwaysOnTop(false);
                    ProductosService.PUT(p);
                    JOptionPane.showMessageDialog(null, "Se ha actualizado correctamente");
                    this.dispose();
                }

        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCerrarWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarWindowMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarWindowMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        mPosX = evt.getX();
        mPosY = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int newPos[] = {evt.getXOnScreen() - mPosX, evt.getYOnScreen() - mPosY};
        this.setLocation(newPos[0], newPos[1]);

    }//GEN-LAST:event_headerMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductoDialog dialog = new ProductoDialog(new javax.swing.JFrame(), true, null, ConsultaActionModes.CREAR);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnCerrarWindow;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> cboxProveedor;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDirección;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblNIT;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSpinner spnDisponible;
    private javax.swing.JSpinner spnPrecioCompra;
    private javax.swing.JSpinner spnPrecioVenta;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
