/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.views.modals;

import com.mycompany.models.Proveedor;
import com.mycompany.models.ConsultaActionModes;
import com.mycompany.services.ClientesService;
import com.mycompany.services.ProveedorService;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class ProveedorDialog extends javax.swing.JDialog {

    /**
     * Creates new form ClienteDialog
     */

    String nombrePH = "";
    String direccionPH = "";
    String telefonoPH = "";
    ClientesService _clienteService;
    Proveedor _proveedor = null;
    ConsultaActionModes modo = ConsultaActionModes.CREAR;
    ArrayList<JTextField> txts;
    int mPosX;
    int mPosY;
    public ProveedorDialog(java.awt.Frame parent, boolean modal, Proveedor proveedor, ConsultaActionModes modo) {
        super(parent, modal);
        initComponents();
        txts = new ArrayList<JTextField>();
        txts.add(txtNombre);
        txts.add(txtDireccion);
        txts.add(txtTelefono);
        this.modo = (modo != null) ? modo : null;
        this._clienteService = new ClientesService();
        this.getPlaceHolders();
        if (modo == ConsultaActionModes.CONSULTAR) {
            _proveedor = proveedor;
            lblTitle.setText("Proveedor Consultado");
            btnCrear.setText("Aceptar");
            jPanel1.remove(btnCancelar);
            jPanel1.revalidate();
            jPanel1.repaint();

            establecerNoEditableTodo();
            rellenarDatos();
        }
        else if (modo == ConsultaActionModes.ACTUALIZAR){
            _proveedor = proveedor;
            lblTitle.setText("Actualizar");
            this.btnCrear.setText("Actualizar");
            
            rellenarDatos();
        }

    }

    private void establecerNoEditableTodo() {
        txts.forEach(e -> e.setEditable(false));
        txts.forEach(e -> e.setBackground(Color.WHITE));
    }

    private void rellenarDatos() {
        txtNombre.setText(_proveedor.getNombre());
        txtDireccion.setText(_proveedor.getDireccion());
        txtTelefono.setText(_proveedor.getTelefono());
    }

    private void getPlaceHolders() {
        nombrePH = txtNombre.getText();
        direccionPH = txtDireccion.getText();
        telefonoPH = txtTelefono.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblDirección = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnCerrarWindow = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(33, 33, 33));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Crear Proveedor");
        background.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 40, 570, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(33, 33, 33));
        lblNombre.setText("Nombre");
        lblNombre.setFocusCycleRoot(true);
        background.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Ingrese el nombre");
        txtNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombrenone(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        background.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 210, -1));

        txtDireccion.setForeground(new java.awt.Color(204, 204, 204));
        txtDireccion.setText("Ingrese la dirección");
        txtDireccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDireccionnone(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        background.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 450, -1));

        lblDirección.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDirección.setForeground(new java.awt.Color(33, 33, 33));
        lblDirección.setText("Dirección");
        lblDirección.setFocusCycleRoot(true);
        background.add(lblDirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefono.setText("Ingrese el número de teléfono");
        txtTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefononone(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        background.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 160, -1));
        txtTelefono.getAccessibleContext().setAccessibleName("");

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(33, 33, 33));
        lblTelefono.setText("Teléfono");
        lblTelefono.setFocusCycleRoot(true);
        background.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        header.setBackground(new java.awt.Color(33, 33, 33));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/src/test.png"))); // NOI18N
        btnCerrarWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarWindowMouseClicked(evt);
            }
        });
        header.add(btnCerrarWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 30));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 30));

        jSeparator2.setBackground(new java.awt.Color(30, 30, 30));
        jSeparator2.setForeground(new java.awt.Color(30, 30, 30));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 160, 10));

        jSeparator4.setBackground(new java.awt.Color(30, 30, 30));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 210, -1));

        jSeparator5.setBackground(new java.awt.Color(30, 30, 30));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 450, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 1, 100, 0));

        btnCrear.setBackground(new java.awt.Color(13, 110, 253));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.setPreferredSize(new java.awt.Dimension(30, 45));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear);

        btnCancelar.setBackground(new java.awt.Color(220, 53, 69));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrenone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombrenone
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrenone

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        if (txtNombre.getText().equals(nombrePH)) {
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDireccionnone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionnone
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionnone

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        // TODO add your handling code here:
        if (txtDireccion.getText().equals(direccionPH)) {
            txtDireccion.setText("");
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtTelefononone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefononone
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefononone

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        if (txtTelefono.getText().equals(telefonoPH)) {
            txtTelefono.setText("");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombre = txtNombre.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        switch (this.modo) {
            case ConsultaActionModes.CREAR:

                if (nombre.isEmpty() || direccion.isEmpty()  || telefono.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No puede dejar los campos en blanco");
                    this.dispose();
                    return;

                } else {
                    this.setModal(false);
                    this.setAlwaysOnTop(false);
                    Proveedor p = new Proveedor(nombre, direccion, telefono);
                    ProveedorService.post(p);
                    JOptionPane.showMessageDialog(null, "Se ha creado correctamente");
                    this.dispose();
                }
                break;
            case ConsultaActionModes.CONSULTAR:
                this.dispose();
                break;
            case ConsultaActionModes.ACTUALIZAR:
                if (nombre.isEmpty() || direccion.isEmpty()  || telefono.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No puede dejar los campos en blanco");
                    this.dispose();
                    return;

                } else {
                    this.setModal(false);
                    this.setAlwaysOnTop(false);
                    Proveedor p = new Proveedor(nombre, direccion ,telefono);
                    p.setProveedor_id(this._proveedor.getProveedor_id());
                    ProveedorService.PUT(p);;
                    JOptionPane.showMessageDialog(null, "Se ha actualizado correctamente");
                    this.dispose();
                }

        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCerrarWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarWindowMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarWindowMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        mPosX = evt.getX();
        mPosY = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int newPos[] = {evt.getXOnScreen() - mPosX, evt.getYOnScreen() - mPosY};
        this.setLocation(newPos[0], newPos[1]);
        
    }//GEN-LAST:event_headerMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProveedorDialog dialog = new ProveedorDialog(new javax.swing.JFrame(), true, null, ConsultaActionModes.CREAR);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnCerrarWindow;
    private javax.swing.JButton btnCrear;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblDirección;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
