/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.views.modals;

import com.mycompany.models.Compra;
import com.mycompany.models.DetalleCompra;
import com.mycompany.models.ConsultaActionModes;
import com.mycompany.models.ConsultaDialogModes;
import com.mycompany.models.DetalleVenta;
import com.mycompany.models.HeaderColor;
import com.mycompany.models.Producto;
import com.mycompany.services.ClientesService;
import com.mycompany.services.CompraService;
import com.mycompany.services.ProductosService;
import com.mycompany.views.modals.ClienteDialog;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author PC
 */
public class SeleccionarProductoCompra extends javax.swing.JDialog {

    /**
     * Creates new form consultarDialog
     */
    int mPosX, mPosY;
    String codigoPH;
    int seleccionTabla;
    DetalleCompra detalleCompra;
    ArrayList<DetalleCompra> detallesCompra;
    TableRowSorter<TableModel> sorter;
    String productoSeleccionado;
    public SeleccionarProductoCompra(java.awt.Frame parent, boolean modal, ArrayList<DetalleCompra> detalles) {
        super(parent, modal);
        initComponents();
        detalleCompra = new DetalleCompra();
        codigoPH = this.txtCodigo.getText();
        detallesCompra = detalles;
        seleccionTabla = -1;
        tblShowProductos.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblShowProductos.getTableHeader().setPreferredSize(new Dimension(tblShowProductos.getTableHeader().getWidth(), 25));
        sorter = new TableRowSorter<>(tblShowProductos.getModel());
        tblShowProductos.setRowSorter(sorter);
        CargarDatos();

    }

    private void CargarDatos() {
        try {

            DefaultTableModel model = (DefaultTableModel) this.tblShowProductos.getModel();
            model.setRowCount(0);
            ArrayList<Producto> productos = ProductosService.getAll();
            productos.forEach((p) -> model.addRow(new Object[]{p.getCodigo(), p.getNombre(), p.getDisponible(), p.getPrecio_Compra(), p.getProveedor()}));
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    private void AgregarProducto(ArrayList<DetalleCompra> lista, DetalleCompra nuevoDetalle) {
        boolean productoExiste = false;
        
        nuevoDetalle.setUnidades((int) this.spnCantidad.getValue());
        // Buscar si el producto ya está en la lista
        for (DetalleCompra detalle : lista) {
            System.out.println("Detalle: " + detalle.getCodigo_producto());
            if (detalle.getCodigo_producto().equals(nuevoDetalle.getCodigo_producto())) {
                // Producto encontrado, sumamos la unidad
                System.out.println("Producto igual");
                System.out.println("Operacion: " + detalle.getUnidades() + " + " + nuevoDetalle.getUnidades());
                detalle.setUnidades(detalle.getUnidades() + nuevoDetalle.getUnidades());
                System.out.println("Nuevas unidades: " + detalle.getUnidades());
                detalle.CalcularSubTotal();
                productoExiste = true;
                break;
            }
        }

        // Si el producto no existe, lo añadimos a la lista
        if (!productoExiste) {
            nuevoDetalle.CalcularSubTotal();
            lista.add(nuevoDetalle);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblCantidad = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        btnCerrarWindow = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowProductos = new javax.swing.JTable();
        lblNIT1 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(450, 256));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(33, 33, 33));
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCantidad.setText("Cantidad");
        lblCantidad.setFocusCycleRoot(true);
        background.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 60, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(33, 33, 33));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Selecciona un producto");
        background.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 850, -1));

        txtCodigo.setForeground(new java.awt.Color(204, 204, 204));
        txtCodigo.setText("Ingresa el código");
        txtCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigonone(evt);
            }
        });
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        background.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 200, -1));

        btnAceptar.setBackground(new java.awt.Color(13, 110, 253));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setLabel("Aceptar");
        btnAceptar.setPreferredSize(new java.awt.Dimension(30, 45));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        background.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 100, 30));

        btnCancelar.setBackground(new java.awt.Color(220, 53, 69));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        background.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 100, 30));

        header.setBackground(new java.awt.Color(33, 33, 33));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/src/test.png"))); // NOI18N
        btnCerrarWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarWindowMouseClicked(evt);
            }
        });
        header.add(btnCerrarWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 30));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 30));

        jSeparator3.setBackground(new java.awt.Color(30, 30, 30));
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, 10));

        tblShowProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Disponible", "Precio Compra", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblShowProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShowProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShowProductos);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 790, 280));

        lblNIT1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNIT1.setForeground(new java.awt.Color(33, 33, 33));
        lblNIT1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNIT1.setText("Buscar por código");
        lblNIT1.setFocusCycleRoot(true);
        background.add(lblNIT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, -1));

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        background.add(spnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigonone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigonone
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigonone

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        //Limpiar el placeholder al escribir dentro del field
        if (txtCodigo.getText().equals(this.codigoPH)) {
            txtCodigo.setText("");
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (this.seleccionTabla >= 0) {

            AgregarProducto(detallesCompra, detalleCompra);
            this.dispose();
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarWindowMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarWindowMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        this.mPosX = evt.getX();
        this.mPosY = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int newPos[] = {mPosX, mPosY};
        this.setLocation(evt.getXOnScreen() - mPosX, evt.getYOnScreen() - mPosY);
    }//GEN-LAST:event_headerMouseDragged

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void tblShowProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShowProductosMouseClicked
        // TODO add your handling code here:
        this.seleccionTabla = tblShowProductos.getSelectedRow();
        if (seleccionTabla >=0){
            this.productoSeleccionado = this.tblShowProductos.getValueAt(seleccionTabla, 0).toString();
            Producto p = new Producto();
            p = ProductosService.Get(this.productoSeleccionado);
            detalleCompra.setProveedor(p.getProveedor());
            detalleCompra.setCodigo_producto(p.getCodigo());
            detalleCompra.setPrecio_compra(p.getPrecio_Compra());
            detalleCompra.setProveedor_id(p.getProveedor_id());
            detalleCompra.setNombre_producto(p.getNombre());
        }
       



    }//GEN-LAST:event_tblShowProductosMouseClicked

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        // TODO add your handling code here:
        String text = txtCodigo.getText();
        if (text.trim().length() == 0) {
            sorter.setRowFilter(null);  // Sin filtro
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));  // Filtrado
        }
    }//GEN-LAST:event_txtCodigoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProductoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProductoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProductoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProductoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionarProductoCompra dialog = new SeleccionarProductoCompra(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnCerrarWindow;
    private javax.swing.JPanel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblNIT1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblShowProductos;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
