/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.views.modals;

import com.mycompany.application.AppInformation;
import com.mycompany.models.Producto;
import com.mycompany.models.Venta;
import com.mycompany.models.Cliente;
import com.mycompany.models.ConsultaActionModes;
import com.mycompany.models.DetalleVenta;
import com.mycompany.models.HeaderColor;
import com.mycompany.models.Proveedor;
import com.mycompany.services.ClientesService;
import com.mycompany.services.ProductosService;
import com.mycompany.services.ProveedorService;
import com.mycompany.services.VentaService;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class VentaDialog extends javax.swing.JDialog {

    /**
     * Creates new form ClienteDialog
     */
    String nitPH = "";
    ConsultaActionModes modo = ConsultaActionModes.CREAR;
    ArrayList<DetalleVenta> detalles;
    int mPosX;
    int mPosY;
    int total;
    Venta ventaConsultada;

    public VentaDialog(java.awt.Frame parent, boolean modal, Venta ventaConsultada, ConsultaActionModes modo) {
        super(parent, modal);
        initComponents();
        this.ventaConsultada = ventaConsultada;
        tblProductos.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblProductos.getTableHeader().setPreferredSize(new Dimension(tblProductos.getTableHeader().getWidth(), 25));
        this.modo = (modo != null) ? modo : null;
        this.nitPH = txtNIT.getText();
        this.detalles = new ArrayList<>();
        this.txtResponsable.setText(AppInformation.getCurrentUser());
        if (modo == ConsultaActionModes.CONSULTAR) {
            txtNIT.setEnabled(false);
            btnAgregarProducto.setEnabled(false);
            btnEliminarProducto.setEnabled(false);
            btnCrear.setText("Aceptar");
            CargarVentaConsultada();
        } else if (modo == ConsultaActionModes.ACTUALIZAR) {
            btnCrear.setText("Actualizar");
            CargarVentaConsultada();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblResponsable = new javax.swing.JLabel();
        txtResponsable = new javax.swing.JTextField();
        header = new javax.swing.JPanel();
        btnCerrarWindow = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblCliente1 = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(246, 246, 246));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(33, 33, 33));
        lblCliente.setText("Total");
        lblCliente.setFocusCycleRoot(true);
        background.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Generar Venta");
        background.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 40, 890, -1));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(204, 204, 204));
        txtTotal.setText("Q0");
        txtTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtTotal.setCaretColor(new java.awt.Color(51, 51, 51));
        txtTotal.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtTotal.setEnabled(false);
        txtTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTotalnone(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });
        background.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 418, 170, 30));

        lblResponsable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResponsable.setForeground(new java.awt.Color(33, 33, 33));
        lblResponsable.setText("Responsable de venta");
        lblResponsable.setFocusCycleRoot(true);
        background.add(lblResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        txtResponsable.setForeground(new java.awt.Color(30, 30, 30));
        txtResponsable.setText("Responsable");
        txtResponsable.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtResponsable.setEnabled(false);
        txtResponsable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtResponsablenone(evt);
            }
        });
        txtResponsable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResponsableKeyTyped(evt);
            }
        });
        background.add(txtResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 130, -1));

        header.setBackground(new java.awt.Color(33, 33, 33));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/src/test.png"))); // NOI18N
        btnCerrarWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarWindowMouseClicked(evt);
            }
        });
        header.add(btnCerrarWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 30));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        btnEliminarProducto.setBackground(new java.awt.Color(63, 81, 181));
        btnEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEliminarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarProducto.setPreferredSize(new java.awt.Dimension(30, 45));
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        background.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 130, 30));

        btnCancelar.setBackground(new java.awt.Color(220, 53, 69));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        background.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 100, 30));

        btnCrear.setBackground(new java.awt.Color(13, 110, 253));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Generar");
        btnCrear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.setPreferredSize(new java.awt.Dimension(30, 45));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        background.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 100, 30));

        tblProductos.setBackground(new java.awt.Color(255, 255, 255));
        tblProductos.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        tblProductos.setForeground(new java.awt.Color(0, 0, 0));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio Unitario", "Cantidad", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblProductos.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tblProductos);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 860, 280));

        lblCliente1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCliente1.setForeground(new java.awt.Color(33, 33, 33));
        lblCliente1.setText("Cliente");
        lblCliente1.setFocusCycleRoot(true);
        background.add(lblCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtNIT.setForeground(new java.awt.Color(204, 204, 204));
        txtNIT.setText("Ingrese el NIT del cliente");
        txtNIT.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtNIT.setCaretColor(new java.awt.Color(51, 51, 51));
        txtNIT.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtNIT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNITnone(evt);
            }
        });
        txtNIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNITMouseClicked(evt);
            }
        });
        txtNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNITKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNITKeyTyped(evt);
            }
        });
        background.add(txtNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 170, -1));

        btnAgregarProducto.setBackground(new java.awt.Color(63, 81, 181));
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProducto.setPreferredSize(new java.awt.Dimension(30, 45));
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        background.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 130, 30));

        jSeparator3.setBackground(new java.awt.Color(30, 30, 30));
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 170, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void CargarTabla(ArrayList<DetalleVenta> detalles) {
        DefaultTableModel model = (DefaultTableModel) this.tblProductos.getModel();
        model.setRowCount(0);
        detalles.forEach((p) -> model.addRow(new Object[]{p.getCodigoProducto(), p.getNombreProducto(), p.getPrecio_unitario(), p.getUnidades(), p.getSubTotal()}));
    }

    private void CargarVentaConsultada() {
        txtTotal.setText("Q" + ventaConsultada.getTotal());
        total = ventaConsultada.getTotal();
        txtResponsable.setText(ventaConsultada.getResponsable());
        txtNIT.setText(ventaConsultada.getNitCliente());
        this.detalles = ventaConsultada.getDetalles();
        this.detalles.forEach(p -> System.out.println(p.getCodigoProducto()));
        CargarTabla(ventaConsultada.getDetalles());
    }

    private void CalcularTotal() {
        total = 0;
        detalles.forEach((p) -> total += p.getSubTotal());
        txtTotal.setText("Q" + total);
    }
    private void txtTotalnone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalnone
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalnone

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyTyped

    private void txtResponsablenone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtResponsablenone
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponsablenone

    private void txtResponsableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResponsableKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtResponsableKeyTyped

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed

        int filaSeleccionada = tblProductos.getSelectedRow();
        if (filaSeleccionada < 0) {
            return;
        }
        if (detalles.size() != 1) {
            String codigoProducto = tblProductos.getValueAt(filaSeleccionada, 0).toString();
            for (DetalleVenta detalle : detalles) {
                if (detalle.getCodigoProducto().equals(codigoProducto)) {
                    detalles.remove(detalle);
                    CalcularTotal();
                    CargarTabla(detalles);
                    return;
                }
            }
        }
        detalles.clear();
        CalcularTotal();
        CargarTabla(detalles);
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnCerrarWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarWindowMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarWindowMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        mPosX = evt.getX();
        mPosY = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int newPos[] = {evt.getXOnScreen() - mPosX, evt.getYOnScreen() - mPosY};
        this.setLocation(newPos[0], newPos[1]);

    }//GEN-LAST:event_headerMouseDragged

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        if (this.modo == ConsultaActionModes.CREAR) {

            Venta venta = new Venta();
            venta.setNitCliente(txtNIT.getText());
            venta.setResponsable(txtResponsable.getText());
            venta.setResponsable_id(AppInformation.getCurrentUserId());
            venta.setTotal(total);
            if (verificarCampos()) {
                VentaService.Post(venta, detalles);
                this.setAlwaysOnTop(false);
                JOptionPane.showMessageDialog(null, "Venta creada correctamente");
                this.dispose();
            } else {
                this.setAlwaysOnTop(false);
                JOptionPane.showMessageDialog(null, "Verifique los campos");
            }
        } else if (this.modo == ConsultaActionModes.ACTUALIZAR) {
            if (verificarCampos()) {
                ventaConsultada.setDetalles(detalles);
                ventaConsultada.setNitCliente(txtNIT.getText());
                ventaConsultada.setResponsable(txtResponsable.getText());
                ventaConsultada.setResponsable_id(AppInformation.getCurrentUserId());
                ventaConsultada.setTotal(total);
                VentaService.put(ventaConsultada);
                this.setAlwaysOnTop(false);
                JOptionPane.showMessageDialog(null, "Venta creada correctamente");
                this.dispose();
            } else {
                this.setAlwaysOnTop(false);
                JOptionPane.showMessageDialog(null, "Verifique los campos");
            }
        }

    }//GEN-LAST:event_btnCrearActionPerformed
    private boolean verificarCampos() {
        //Verificar si el NIT existe
        boolean existeNIT = false;
        ClientesService clienteService = new ClientesService();
        ArrayList<Cliente> listaClientes = clienteService.consultarClientes();
        for (Cliente cliente : listaClientes) {
            if (cliente.getNIT().equals(txtNIT.getText())) {
                existeNIT = true;
            }
        }
        if (existeNIT && detalles.size() > 0) {
            return true;
        }
        System.out.println("detalles size " + detalles.size());
        return false;
    }
    private void txtNITnone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNITnone
        // TODO add your handling code here:
        if (txtNIT.getText().equals(nitPH)) {
            txtNIT.setText("");
        } else {
            txtNIT.setForeground(new Color(30, 30, 30));
        }
    }//GEN-LAST:event_txtNITnone

    private void txtNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNITKeyTyped
        // TODO add your handling code here:
        txtNIT.setForeground(new Color(30, 30, 30));
    }//GEN-LAST:event_txtNITKeyTyped

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
        //Abrimos la ventana para agregar producto
        SeleccionarProductoDialog _dialog = new SeleccionarProductoDialog(null, true, detalles);
        _dialog.setAlwaysOnTop(true);
        _dialog.setLocationRelativeTo(null);
        _dialog.setVisible(true);
        CargarTabla(detalles);
        CalcularTotal();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void txtNITKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNITKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_txtNITKeyReleased

    private void txtNITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNITMouseClicked
        // TODO add your handling code here:
        txtNIT.setForeground(new Color(30, 30, 30));
    }//GEN-LAST:event_txtNITMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentaDialog dialog = new VentaDialog(new javax.swing.JFrame(), true, null, ConsultaActionModes.CREAR);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnCerrarWindow;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JPanel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtResponsable;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
