/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.services.ClientesService;
import javax.management.modelmbean.ModelMBean;
import com.mycompany.models.Compra;
import com.mycompany.models.ConsultaActionModes;
import com.mycompany.models.ConsultaDialogModes;
import com.mycompany.models.HeaderColor;
import com.mycompany.services.CompraService;
import com.mycompany.views.modals.ClienteDialog;
import com.mycompany.views.modals.CompraDialog;
import com.mycompany.views.modals.ConsultarDialog;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author PC
 */
public class GestionComprasView extends javax.swing.JPanel {

    /**
     * Creates new form Form
     */
    ClientesService _clientesService = ClientesService.getInstance();
    String filtrarPH;
    TableRowSorter<TableModel> sorter;
    int totalCompras = 0;
    int filaSeleccionada = -1;
    int compraSeleccionada;
    public GestionComprasView() {
        initComponents();
        this.filtrarPH = txtFiltrar.getText();
        tblCompras.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblCompras.getTableHeader().setPreferredSize(new Dimension(tblCompras.getTableHeader().getWidth(), 25));
        sorter = new TableRowSorter<>(tblCompras.getModel());
        CargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void CargarDatos() {
        try {
            
            DefaultTableModel model = (DefaultTableModel) this.tblCompras.getModel();
            this.totalCompras = CompraService.getTotalCompras();
            lblTotalCompras.setText("Total de compras: Q"+totalCompras);
            model.setRowCount(0);
            ArrayList<Compra> clientes = CompraService.getAllCompras();
            clientes.forEach((p) -> model.addRow(new Object[]{p.getCompra_id(), p.getUsuario(), p.getFecha(), p.getTotal()}));
        }catch(Exception e){
            System.out.println(e);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrear = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblFiltrar = new javax.swing.JLabel();
        txtFiltrar = new javax.swing.JTextField();
        lblTotalCompras = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 610));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 610));
        setRequestFocusEnabled(false);

        btnCrear.setBackground(new java.awt.Color(13, 110, 253));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.setPreferredSize(new java.awt.Dimension(30, 45));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(108, 117, 125));
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnEliminar1.setBackground(new java.awt.Color(220, 53, 69));
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEliminar1.setBorderPainted(false);
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(13, 110, 253));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        tblCompras.setBackground(new java.awt.Color(255, 255, 255));
        tblCompras.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        tblCompras.setForeground(new java.awt.Color(0, 0, 0));
        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Compra", "Responsable", "Fecha", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCompras.setRowHeight(25);
        tblCompras.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblCompras.setShowGrid(false);
        tblCompras.setShowHorizontalLines(true);
        tblCompras.getTableHeader().setReorderingAllowed(false);
        tblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCompras);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Gestionar Compras");

        lblFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFiltrar.setForeground(new java.awt.Color(33, 33, 33));
        lblFiltrar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFiltrar.setText("Filtrar");
        lblFiltrar.setFocusCycleRoot(true);

        txtFiltrar.setForeground(new java.awt.Color(204, 204, 204));
        txtFiltrar.setText("Ingresa para filtrar");
        txtFiltrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));
        txtFiltrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFiltrarnone(evt);
            }
        });
        txtFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltrarActionPerformed(evt);
            }
        });
        txtFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltrarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltrarKeyTyped(evt);
            }
        });

        lblTotalCompras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalCompras.setForeground(new java.awt.Color(33, 33, 33));
        lblTotalCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalCompras.setText("Total de compras:");
        lblTotalCompras.setFocusCycleRoot(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lblTotalCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFiltrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotalCompras)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents
        private void limpiarFields() {
        /*
        txtNIT.setText("");
        txtNIT.setEditable(true);
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTel.setText("");
        txtCorreo.setText("");
         */
    }

    private void establecerNoEditableTodo() {
        /*
        txtNIT.setEditable(false);
        txtNombre.setEditable(false);
        txtDireccion.setEditable(false);
        txtTel.setEditable(false);
        txtCorreo.setEditable(false);
         */

    }
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        CompraDialog _view = new CompraDialog(null, true, null, ConsultaActionModes.CREAR);
        _view.setLocationRelativeTo(null);
        _view.setAlwaysOnTop(true);
        _view.setVisible(true);
        this.CargarDatos();
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        ConsultarDialog _dialog = new ConsultarDialog(null, true, null,ConsultaDialogModes.Compra, ConsultaActionModes.CONSULTAR);
        _dialog.setLocationRelativeTo(null);
        _dialog.setAlwaysOnTop(true);
        _dialog.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (this.filaSeleccionada >=0){
            Compra compraSelec = CompraService.getCompra(this.compraSeleccionada);
            CompraDialog _dialog = new CompraDialog(null, true, compraSelec, ConsultaActionModes.ACTUALIZAR);
            _dialog.setLocationRelativeTo(null);
            _dialog.setVisible(true);
        }
        this.CargarDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        if (this.filaSeleccionada >=0){
            int result = JOptionPane.showConfirmDialog(null, "¿Estás seguro que quieres eliminar este elemento?");
            if (result == 0){
                CompraService.eliminarCompra(compraSeleccionada);
                this.CargarDatos();
            }
        }
        
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void txtFiltrarnone(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFiltrarnone
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltrarnone

    private void txtFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltrarActionPerformed

    private void txtFiltrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarKeyReleased
        // TODO add your handling code here:
        String text = txtFiltrar.getText();
        if (text.trim().length() == 0) {
            sorter.setRowFilter(null);  // Sin filtro
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));  // Filtrado
        }
    }//GEN-LAST:event_txtFiltrarKeyReleased

    private void txtFiltrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarKeyTyped
        // TODO add your handling code here:
        //Limpiar el placeholder al escribir dentro del field
        if (txtFiltrar.getText().equals(this.filtrarPH)) {
            txtFiltrar.setText("");
        }
    }//GEN-LAST:event_txtFiltrarKeyTyped

    private void tblComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprasMouseClicked
        // TODO add your handling code here:
        this.filaSeleccionada = tblCompras.getSelectedRow();
        this.compraSeleccionada =(int) tblCompras.getValueAt(this.filaSeleccionada, 0);
    }//GEN-LAST:event_tblComprasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCompras;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTextField txtFiltrar;
    // End of variables declaration//GEN-END:variables
}
